# Generated by Django 4.0.4 on 2022-06-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userlog_last_apply_alter_userlog_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='last_Apply',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
