# Generated by Django 4.0.4 on 2022-06-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userlog_last_apply_alter_userlog_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, verbose_name='이름'),
        ),
    ]
